### PR TITLE
Makefile mods to work with CMake as ExternalProject

### PR DESCRIPTION
**Pull request by dibsonmuad**
When mseed is added as an ExternalProject to CMake, the installation of
libraries fails silently. The comparison ifneq (wildcard $(LIB_SO))
fails for some reason. This commit creates a common LIB_SO set of
variables for Darwin and Linux so that the ifneq comparison during
install time can be removed.

### CODE REVIEW

**Comment by dibsonmuad** [comment]
Having trouble with Makefile formatting.

**Comment by chad-iris** [comment]
@dibsonmuad Thank you for your contribution.  I have pushed a few commits to your PR to clean up the Makefile and finish the merging of shared and dynamic library building.

I do not know how to test this as an ExternalProject to CMake. If you could verify that the Makefile now works in that scenario I'll merge this change.

**Comment by dibsonmuad** [comment]
I tested it on Darwin and am pasting my CMake snippet used to test. Can confirm that it builds fine.
```
externalproject_add(mseed
    GIT_REPOSITORY "https://github.com/iris-edu/libmseed.git"
    UPDATE_COMMAND git pull origin pull/31/head:master
    SOURCE_DIR mseed
    BUILD_IN_SOURCE 1
    CMAKE_GENERATOR make
    CONFIGURE_COMMAND ""
    ${PROJECT_BINARY_DIR}/mseed
    UPDATE_COMMAND ""
    BUILD_COMMAND make PREFIX=${CMAKE_INSTALL_PREFIX}
    INSTALL_COMMAND  make PREFIX=${CMAKE_INSTALL_PREFIX} install
  )
```

**Comment by chad-iris** [comment]
Thanks for testing and again for contributing @dibsonmuad!

**Pull request merged**
