### PR TITLE
use pkg-config in example/Makefile to link against library

### PR DESCRIPTION
**Pull request by duperray**
Now, that we have a .pc file for pkg-config, we can use it in the example/Makefile

### CODE REVIEW

**Comment by chad-iris** [comment]
The .pc file is not available until *after* an 'install' (which only installs dynamic libraries), i.e. the examples are not build-able unless shared libraries have been installed.  That's not acceptable.

I can see why it's a problem for the installed examples as they would not build without modification.   

I see two alternatives:
a) do _not_ install the examples (are they really needed for every install?) or
b) modify the example/Makefile during installation to use pkg-config

**Comment by duperray** [comment]
I though, the example where meant to be used after the install.
In debian packaging, they are used to check the library is well installed, and that the pkg-config file
are installed and usable.

**Comment by chad-iris** [comment]
Prior to a few days ago there was no install method at all.  Nearly all of my own usage is to embed the library into a project (using the static library build) and is never installed system-wide on the machine.  I think that style of usage is the most prevalent.

**Comment by duperray** [comment]
ok, I think it's better to close this, I will only use this patch for debian. Sorry for the noise

**Pull request closed without merging**
